import { createElement, useContext } from "react";

import { generateClassNames } from "./generateClassNames";
import { Elements, Flags, Token } from "./types";
import { ThemeContext } from "./context";
import { RefContext, withRef } from "./ref";

type StyleProps<T extends Flags> = {
  [K in keyof T]: keyof T[K];
};

type WindComponentProps<T extends Flags, K extends Elements> = Partial<
  StyleProps<T>
> &
  JSX.IntrinsicElements[K] & { as?: Elements };

export interface WindComponent<T extends Flags, K extends Elements> {
  (props: WindComponentProps<T, K>): JSX.Element;
  withRef: (displayName?: string) => WindComponent<T, K>;
}

interface CreateComponentParams {
  element: Elements;
  flags: Flags;
  tokens: Token[];
}

export function createComponent<T extends Flags, K extends Elements>({
  element,
  flags,
  tokens,
}: CreateComponentParams) {
  const Component = (props: WindComponentProps<T, K>) => {
    const { processor } = useContext(ThemeContext);
    const { ref } = useContext(RefContext);
    const { as = element, ...rest } = props;
    //TODO: fix
    const htmlTag = (as ? as : element) as keyof JSX.IntrinsicElements;
    let flagProps: Record<string, any> = {};
    let componentProps: Record<string, any> = {};

    // Separate the html element props and flag props
    // e.g onClick, className, aria etc goes to `componentProps`
    // custom props generated by tswind goes to `flagProps`
    for (const key in rest) {
      if (Object.keys(flags).includes(key)) {
        flagProps[key] = rest[key];
      } else {
        componentProps[key] = rest[key];
      }
    }

    const className = generateClassNames({
      flags,
      flagProps,
      tokens,
      themeTokenProcessor: processor,
    }).trim();

    return createElement(htmlTag, {
      ref,
      ...(className ? { className } : {}),
      ...componentProps,
    });
  };

  (Component as any)._flags = flags;
  (Component as any)._tokens = tokens;
  (Component as any).withRef = (displayName?: string) =>
    withRef(Component as any, displayName);

  return Component;
}
